// @ts-check

/**
 * Page Object Model for the UND (Ukraine Nintendo Daily) homepage.
 * Generated by the generate-pom skill from a live browser_snapshot of https://und.com.ua/
 */
class HomePage {
  /** @param {import('@playwright/test').Page} page */
  constructor(page) {
    this.page = page;

    // Accessibility
    this.skipToContentLink = page.getByRole('link', { name: 'Перейти до змісту' });

    // Header / branding
    this.logoLink = page.getByRole('link', { name: 'UKRAINE NINTENDO DAILY' });

    // Top utility bar
    this.supportUkraineLink = page.getByRole('link', { name: 'Підтримати ЗСУ' });

    // Language switcher — a native <details> disclosure, so `open` reflects its state.
    this.langDropdown = page.locator('details.und-lang-dropdown');
    this.langToggle = this.langDropdown.locator('summary');
    this.langUkOption = this.langDropdown.getByRole('link', { name: /Українська/ });
    this.langEnOption = this.langDropdown.getByRole('link', { name: /Англійська/ });

    // Mobile layout: the hamburger opens its own dropdown panel with a distinct set of
    // links (it adds "Змагання"/"Рейтинг SSBU" and inlines the language links). It is a
    // separate component from the desktop nav, not a re-render of it, and it carries no
    // search field — search simply does not exist in the mobile layout.
    this.hamburgerButton = page.getByRole('button', { name: 'Меню' });
    this.mobileMenu = page.locator('div.und-mobile-menu');
    this.mobileMenuLangUk = this.mobileMenu.getByRole('link', { name: /Українська/ });
    this.mobileMenuLangEn = this.mobileMenu.getByRole('link', { name: /Англійська/ });

    // Primary navigation (desktop layout only — hidden behind the hamburger on mobile)
    this.nav = page.locator('nav.und-header__nav');
    this.navNewsLink = this.nav.getByRole('link', { name: 'Новини' });
    this.navEditorialLink = this.nav.getByRole('link', { name: 'Авторські огляди' });
    this.navTournamentsLink = this.nav.getByRole('link', { name: 'Турніри' });
    this.navCalendarLink = this.nav.getByRole('link', { name: 'Календар' });
    this.navTvLink = this.nav.getByRole('link', { name: 'UND TV' });

    // Search
    this.searchInput = page.getByPlaceholder('Пошук...');
    this.searchButton = page.getByRole('button', { name: 'Пошук' });

    // Auth
    this.loginLink = page.getByRole('link', { name: 'Увійти' });

    // Cookie consent banner (shown on first load)
    this.cookieAcceptButton = page.getByRole('button', { name: 'Я погоджуюсь' });
    this.cookieNecessaryOnlyButton = page.getByRole('button', { name: 'Тільки найнеобхідніше' });

    // Main content — mainHeading is the featured story's headline, so its text
    // changes with content; the role/level selector itself stays stable.
    this.mainHeading = page.getByRole('heading', { level: 1 });
    this.heroLink = page.locator('main a').first();
    this.freshNewsHeading = page.getByRole('heading', { name: 'Свіжі новини', level: 2 });
    // Class-anchored rather than positional: the number of <nav> landmarks differs
    // between the desktop and mobile layouts, so an nth() index is not stable.
    this.categoryFilterNav = page.locator('nav.und-category-tabs');
    this.articleCards = page.getByRole('article');
    this.nextPageLink = page.getByRole('link', { name: 'Наступна сторінка' });
    this.pagination = page.getByRole('navigation').last();

    // UND TV section
    this.undTvHeading = page.getByRole('heading', { name: 'UND TV', level: 2 });
    this.undTvYoutubeLink = page.getByRole('link', { name: 'Перейти на YouTube' });

    // Footer
    this.footer = page.getByRole('contentinfo');
    this.newsletterEmailInput = this.footer.getByPlaceholder('Ел. пошта');
    this.newsletterSubmitButton = this.footer.getByRole('button', { name: 'OK' });
  }

  async goto() {
    // domcontentloaded, а не дефолтний load: сторінка тягне рекламу й трекери, на які
    // жоден асерт не спирається, а очікування їх додає кілька секунд до кожної навігації.
    // Видимість елементів усе одно гарантує автоочікування локаторів.
    await this.page.goto('/', { waitUntil: 'domcontentloaded' });
  }

  /**
   * Банер згоди вставляється скриптом приблизно через 1.5 с ПІСЛЯ domcontentloaded —
   * одразу після навігації його в DOM ще немає. Тому кожна взаємодія з ним іде через
   * це очікування, інакше під навантаженням тест падає з "element not found".
   *
   * 10 с — це ~6× від заміряної затримки: достатньо під навантаженням, але свідомо
   * набагато менше за таймаут тесту. Разом із навігацією beforeEach має вкладатися
   * в бюджет тесту із запасом, інакше хук зʼїдає його весь і падає узагальненою
   * помилкою замість конкретної.
   * @param {number} [timeout]
   */
  async waitForConsentBanner(timeout = 10_000) {
    await this.cookieAcceptButton.waitFor({ state: 'visible', timeout });
  }

  /**
   * Приймає повну згоду, якщо банер показано. Банер керується cookie, тож на вже
   * «згодженому» контексті його не буде — це не помилка, тому хелпер тихо виходить.
   * Тести, для яких сам банер є предметом перевірки, спершу викликають
   * waitForConsentBanner() і асертять видимість явно.
   */
  async acceptCookies() {
    try {
      await this.waitForConsentBanner();
    } catch {
      return;
    }
    await this.cookieAcceptButton.click();
  }

  /** Приймає лише необхідні cookies. Банер тут обовʼязковий — його відсутність є помилкою. */
  async acceptNecessaryCookiesOnly() {
    await this.waitForConsentBanner();
    await this.cookieNecessaryOnlyButton.click();
  }

  /**
   * Reads the site's stored consent cookie, which records `optional: true` for full
   * consent and `optional: false` for necessary-only. Returns null before any choice.
   * @returns {Promise<{required: boolean, optional: boolean, ts: number} | null>}
   */
  async getConsentCookie() {
    const cookies = await this.page.context().cookies();
    const consent = cookies.find((c) => c.name === 'website_cookies_bar');
    if (!consent) return null;
    return JSON.parse(decodeURIComponent(consent.value));
  }

  /** @param {string} query */
  async search(query) {
    await this.searchInput.fill(query);
    await this.searchButton.click();
  }

  /** @param {string} name */
  async goToNav(name) {
    await this.nav.getByRole('link', { name }).click();
  }

  /** @param {string} title */
  async openArticleByTitle(title) {
    await this.articleCards.filter({ hasText: title }).getByRole('link').first().click();
  }

  /**
   * Точний збіг обовʼязковий: назви категорій перекриваються
   * (напр. "Pokémon" є префіксом "Pokémon Pokopia").
   * @param {string} name
   */
  async filterByCategory(name) {
    await this.categoryFilterNav.getByRole('link', { name, exact: true }).click();
  }

  async goToNextPage() {
    await this.nextPageLink.click();
  }

  /** Opens the language disclosure and switches the site to English. */
  async switchToEnglish() {
    await this.langToggle.click();
    await this.langEnOption.click();
  }

  /** @param {string} email */
  async subscribeToNewsletter(email) {
    await this.newsletterEmailInput.fill(email);
    await this.newsletterSubmitButton.click();
  }
}

module.exports = { HomePage };
